# Generated by Django 5.1.1 on 2024-09-28 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=32, verbose_name='login')),
                ('password', models.CharField(max_length=32, verbose_name='password')),
                ('key', models.IntegerField(verbose_name='key')),
                ('status', models.BooleanField(verbose_name='status')),
            ],
        ),
    ]
