# Generated by Django 5.1.2 on 2024-11-10 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_users_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='key',
            field=models.CharField(max_length=32, verbose_name='key'),
        ),
    ]
