# Generated by Django 5.1.1 on 2025-10-27 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_users_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='role',
            field=models.CharField(choices=[('admin', 'Администратор'), ('moderator', 'Модератор'), ('regular', 'Обычный пользователь')], default='regular', max_length=10, verbose_name='role'),
        ),
        migrations.AlterField(
            model_name='users',
            name='authorization',
            field=models.BooleanField(default=False, verbose_name='authorization'),
        ),
    ]
