# Generated by Django 5.1.1 on 2025-10-31 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_users_role_alter_users_authorization'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='users',
            table='user_user',
        ),
    ]
