# Generated by Django 5.1.2 on 2024-11-09 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analyse',
            name='user_id',
        ),
    ]
