# Generated by Django 5.1.2 on 2024-11-10 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_result_analyse_ensemble_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyse',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='image'),
        ),
    ]
