# Generated by Django 5.1.2 on 2024-11-10 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_analyse_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyse',
            name='image',
            field=models.CharField(max_length=128, verbose_name='name'),
        ),
    ]
