# Generated by Django 5.1.2 on 2024-11-10 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_analyse_image'),
        ('users', '0005_alter_users_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyse',
            name='user_key',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='users.users'),
            preserve_default=False,
        ),
    ]
