# Generated by Django 5.1.1 on 2024-12-11 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_analyse_datetime_analyse_description_analyse_patient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyse',
            name='diagnosis',
            field=models.CharField(blank=True, default='Не выбран', max_length=64, verbose_name='diagnosis'),
        ),
    ]
