# Generated by Django 5.1.1 on 2024-12-11 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_analyse_datetime_alter_analyse_image'),
        ('main', '0007_analyse_datetime_analyse_description_analyse_patient_and_more'),
    ]

    operations = [
    ]
