# Generated by Django 5.1.1 on 2025-10-28 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_analyse_diagnosis'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyse',
            name='ensemble_probability',
            field=models.CharField(default='0', max_length=8, verbose_name='ensemble_probability'),
        ),
        migrations.AddField(
            model_name='analyse',
            name='model_1_probability',
            field=models.CharField(default='0', max_length=8, verbose_name='model_1_probability'),
        ),
        migrations.AddField(
            model_name='analyse',
            name='model_2_probability',
            field=models.CharField(default='0', max_length=8, verbose_name='model_2_probability'),
        ),
        migrations.AddField(
            model_name='analyse',
            name='model_3_probability',
            field=models.CharField(default='0', max_length=8, verbose_name='model_3_probability'),
        ),
    ]
