# Generated by Django 5.1.1 on 2024-12-20 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_merge_20241211_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyse',
            name='diagnosis',
            field=models.CharField(blank=True, default='Не выбран', max_length=64, verbose_name='diagnosis'),
        ),
        migrations.AddField(
            model_name='analyse',
            name='ensemble_probability',
            field=models.CharField(default='0', max_length=8, verbose_name='ensemble_probability'),
        ),
        migrations.AddField(
            model_name='analyse',
            name='model_1_probability',
            field=models.CharField(default='0', max_length=8, verbose_name='model_1_probability'),
        ),
        migrations.AddField(
            model_name='analyse',
            name='model_2_probability',
            field=models.CharField(default='0', max_length=8, verbose_name='model_2_probability'),
        ),
        migrations.AddField(
            model_name='analyse',
            name='model_3_probability',
            field=models.CharField(default='0', max_length=8, verbose_name='model_3_probability'),
        )
    ]
