# Generated by Django 5.1.1 on 2024-12-20 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_analyse_diagnosis_analyse_ensemble_probability_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyse',
            name='datetime',
            field=models.CharField(default='-', max_length=128, verbose_name='date'),
        ),
    ]
