# Generated by Django 5.1.1 on 2025-12-02 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_analyse_ensemble_probability_and_more'),
        ('users', '0008_users_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyse',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='is_deleted'),
        ),
        migrations.AddIndex(
            model_name='analyse',
            index=models.Index(fields=['is_deleted'], name='main_analys_is_dele_b14f09_idx'),
        ),
        migrations.AddIndex(
            model_name='analyse',
            index=models.Index(fields=['user_key', 'is_deleted'], name='main_analys_user_ke_73d6fb_idx'),
        ),
    ]
