# Generated by Django 5.1.1 on 2024-12-20 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_analyse_diagnosis'),
        ('main', '0010_alter_analyse_datetime'),
    ]

    operations = [
    ]
